"""Subscriptions, quotas, feature gates and PayChangu integration (Phase 7–8)."""

from .paychangu import PayChanguClient, PayChanguConfig, PayChanguError
from .plans import (
    ALL_FEATURES,
    FEATURE_LABELS,
    PlanSpec,
    all_plans,
    get_plan,
    plan_catalog_payload,
    plan_includes_feature,
    plan_rank,
)
from .repository import BillingRepository
from .service import (
    BillingBlocked,
    activate_plan,
    assert_can_assess,
    assert_feature,
    billing_status,
    cancel_at_period_end,
    change_plan,
    count_assessments_this_month,
    demo_mode_enabled,
    enforcement_enabled,
    feature_check,
    grace_period_days,
    handle_payment_failed,
    payment_history,
    quota_check,
    reactivate,
    record_checkout,
    suspend,
    usage_summary,
)

__all__ = [
    "ALL_FEATURES",
    "FEATURE_LABELS",
    "PlanSpec",
    "all_plans",
    "get_plan",
    "plan_catalog_payload",
    "plan_includes_feature",
    "plan_rank",
    "BillingRepository",
    "BillingBlocked",
    "activate_plan",
    "assert_can_assess",
    "assert_feature",
    "billing_status",
    "cancel_at_period_end",
    "change_plan",
    "count_assessments_this_month",
    "demo_mode_enabled",
    "enforcement_enabled",
    "feature_check",
    "grace_period_days",
    "handle_payment_failed",
    "payment_history",
    "quota_check",
    "reactivate",
    "record_checkout",
    "suspend",
    "usage_summary",
    "PayChanguClient",
    "PayChanguConfig",
    "PayChanguError",
]
